### ISSUE TITLE
skip empty tiles

### ISSUE THREAD

**Issue by frulo** [martinheidegger/mapslice#11]
actually Actually mapslice generate lot of empty/blanc tiles. That is a good feature to ensure the same image position for different zoom level. In some cases the user do not need this empty tiles. I make some changes in the code that give the possibility to skip this tiles. I would like to push the changes...

**Comment by martinheidegger** [comment]
@frulo It would be awesome if there was a [Pull Request](https://help.github.com/articles/using-pull-requests/) for that!

**Comment by frulo** [comment]
#12

**Comment by martinheidegger** [comment]
Closing issue as this was merged a while ago.
