### ISSUE TITLE
zoom level customization

### ISSUE THREAD

**Issue by jjhesk** [martinheidegger/mapslice#14]
how to tune the zoom level on each zoom and the number of zooms to be configured? i have found `zoomMin` in the source.

**Comment by martinheidegger** [comment]
The zoom level is following google maps standards and increases by the factor of `2` at every level:

So if we have a tile size of `256`, it takes `256` pixel for the first level then halves it to `512` pixels then to `1024` etc. _(All viewing software that I know is made up to work like this.)_

The tile-size specifies how big/small each zoom level is. If you have an image of `2000`x`2000` for example and a tilesize of `512` the algorithm will search for the first multiple of `2` of the tilesize that fits `2000`.

_Does `2000` fit in `512`(x1)?  **No**. Does `2000` fit in `1024`(x2)? **No**. Does `2000` fit in `2048`(x4)? **Yes**, lets take that as maximum scale level_

The `2000` pixel image is then centered inside the `2048` image and cut in pieces without scaling it! Then its scaled /2 to the size of `1000`, centred and again tiles are cut. and then to /4 `500` which then becomes the smallest size.

### Or
**Alternatively** there is also the [`-w`](https://github.com/martinheidegger/mapslice#size-detection-and-scaling) option. If you specify `-w` the algorithm will work differently.

If you specify `-w` to be `800` then mapslice will do something different: It will first check which tilesize would fit `800`: 

_Does `800` fit in `512`(*1)? **No** . Does `800` fit in `1024`(*)? **Yes** , take this as smallest zoom level!_

It will then calculate the maximum size it can find as multiple of 2:

_Is `800`(x1) smaller than `2000`(the max size)? **Yes**. Is `1600`(x2) smaller than `2000`? **Yes**. Is `3200`(x4) smaller than `2000`? **No**. then lets take `1600` as highest zoom level!_

So it will take the smallest zoom level of `1024` and zoom `2000` → `800` pixels then cut it in `4` tiles of `512`. Then it uses the zoom level of `2048` and scales `2000` → `1600` pixels. 

---

I hope this answers your question on the use of mapslice. Can you fulfill your use-case with that?

**Comment by jjhesk** [comment]
yes. this is very helpful. one more question. are there any extra options to remove the white space?

**Comment by martinheidegger** [comment]
Do you mean the "background" on tiles that are cropped?

**Comment by jjhesk** [comment]
yes. the white background that are found from the left space of the square image.

**Comment by martinheidegger** [comment]
There is a background property that allows to set the background to transparent. I think it would be unwise (for the tools) to crop the white space.

**Comment by jjhesk** [comment]
the transparency is not supported by jpeg however.

**Comment by martinheidegger** [comment]
Yes?!?

**Comment by martinheidegger** [comment]
Closing this issue for now. It seems to be answered.
