### ISSUE TITLE
update to support node5 and node6

### ISSUE THREAD

**Issue by jjhesk** [martinheidegger/mapslice#17]
are you planning on support with version? if so there will need to make separate version of the library because the emitEvent is using different code now.

**Comment by martinheidegger** [comment]
@jjhesk I have just tried the tool in Node 6.5 and it is working fine. What API change are you referring t?

**Comment by martinheidegger** [comment]
Assuming this issue was a non-issue due to not being able to replicate it and due to the lack of an anwer.
