### ISSUE TITLE
Error while fetching size of File

### ISSUE THREAD

**Issue by felstell** [martinheidegger/mapslice#21]
Hello!

I was try to slice my SVG file, but give this error. Earlier I was successfully slice JPG file. 
Can you help me?

<img width="899" alt="2019-02-25 13 13 19" src="https://user-images.githubusercontent.com/8091787/53330261-2334f580-38ff-11e9-9018-3f7fa122e11e.png">

**Comment by martinheidegger** [comment]
I have never tried svg support and I would appreciate a PR with a test for it.

That being said, a SVG can be specified with or without size, I believe without a size gd will result in an error.

**Comment by felstell** [comment]
I was try use script again with some other svg files few minutes ago. Not working. Size from 0,4mb to 1,5mb. All files have metainfo about size. 

Can I help you anyone to solve this problem?

**Comment by martinheidegger** [comment]
graphicsMagick has very poor support for svg. Can you try to use imagemagick?

**Comment by martinheidegger** [comment]
I published an update for mapslice@2.0 which should update a lot of things; Notably for this issue, it contains a error message hinting that this is a problem with graphicsMagick. The .svg support of graphicsMagick is very poor. If it doesn't work, it is my recommendation to try imageMagick or simply transform it into a raster-image beforehand.

I am closing this issue as I believe there is nothing else I can help you with.

**Comment by felstell** [comment]
>graphicsMagick has very poor support for svg. Can you try to use imagemagick?

I was install both libraries, and don't choose one of them. I just start mapslice. 

But thank you. I hope your efforts will not be in vain.

**Comment by martinheidegger** [comment]
Mapslice uses graphicsmagick or imagemagick in the background to process
things. I order to tell mapslice to use imagemagick just pass the '-i'
option to the command line.

**Comment by felstell** [comment]
It works, and works great.

Thank you
